<?php
	echo "HashCode Generated by SHA-1 for:"; 
	echo ("<br>");
	$myString = "hello world";
	echo $myString." : ";
	echo sha1($myString);
	echo ("<br>");
	$myString2 = "GeeksForGeeks";
	echo $myString2." : ";
	echo sha1($myString2);
?>
